workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build AAB
        script: flutter build appbundle

    artifacts:
      - build/app/outputs/bundle/release/*.aab
